package com.netty.pine.common.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/PacketData.proto

public final class PacketDataProto {
  private PacketDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PacketData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 cmd = 1;</code>
     */
    int getCmd();

    /**
     * <code>string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>int32 resultStatus = 3;</code>
     */
    int getResultStatus();

    /**
     * <code>int32 packetId = 4;</code>
     */
    int getPacketId();
  }
  /**
   * Protobuf type {@code PacketData}
   */
  public  static final class PacketData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PacketData)
      PacketDataOrBuilder {
    // Use PacketData.newBuilder() to construct.
    private PacketData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PacketData() {
      cmd_ = 0;
      msg_ = "";
      resultStatus_ = 0;
      packetId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PacketData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cmd_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 24: {

              resultStatus_ = input.readInt32();
              break;
            }
            case 32: {

              packetId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PacketDataProto.internal_static_PacketData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PacketDataProto.internal_static_PacketData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PacketDataProto.PacketData.class, PacketDataProto.PacketData.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>int32 cmd = 1;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTSTATUS_FIELD_NUMBER = 3;
    private int resultStatus_;
    /**
     * <code>int32 resultStatus = 3;</code>
     */
    public int getResultStatus() {
      return resultStatus_;
    }

    public static final int PACKETID_FIELD_NUMBER = 4;
    private int packetId_;
    /**
     * <code>int32 packetId = 4;</code>
     */
    public int getPacketId() {
      return packetId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(1, cmd_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (resultStatus_ != 0) {
        output.writeInt32(3, resultStatus_);
      }
      if (packetId_ != 0) {
        output.writeInt32(4, packetId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (resultStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resultStatus_);
      }
      if (packetId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, packetId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PacketDataProto.PacketData)) {
        return super.equals(obj);
      }
      PacketDataProto.PacketData other = (PacketDataProto.PacketData) obj;

      boolean result = true;
      result = result && (getCmd()
          == other.getCmd());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (getResultStatus()
          == other.getResultStatus());
      result = result && (getPacketId()
          == other.getPacketId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + RESULTSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getResultStatus();
      hash = (37 * hash) + PACKETID_FIELD_NUMBER;
      hash = (53 * hash) + getPacketId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PacketDataProto.PacketData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PacketDataProto.PacketData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PacketDataProto.PacketData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PacketDataProto.PacketData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PacketDataProto.PacketData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PacketDataProto.PacketData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PacketDataProto.PacketData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PacketDataProto.PacketData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PacketDataProto.PacketData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PacketDataProto.PacketData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PacketDataProto.PacketData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PacketData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PacketData)
        PacketDataProto.PacketDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PacketDataProto.internal_static_PacketData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PacketDataProto.internal_static_PacketData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PacketDataProto.PacketData.class, PacketDataProto.PacketData.Builder.class);
      }

      // Construct using PacketDataProto.PacketData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        msg_ = "";

        resultStatus_ = 0;

        packetId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PacketDataProto.internal_static_PacketData_descriptor;
      }

      public PacketDataProto.PacketData getDefaultInstanceForType() {
        return PacketDataProto.PacketData.getDefaultInstance();
      }

      public PacketDataProto.PacketData build() {
        PacketDataProto.PacketData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PacketDataProto.PacketData buildPartial() {
        PacketDataProto.PacketData result = new PacketDataProto.PacketData(this);
        result.cmd_ = cmd_;
        result.msg_ = msg_;
        result.resultStatus_ = resultStatus_;
        result.packetId_ = packetId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PacketDataProto.PacketData) {
          return mergeFrom((PacketDataProto.PacketData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PacketDataProto.PacketData other) {
        if (other == PacketDataProto.PacketData.getDefaultInstance()) return this;
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getResultStatus() != 0) {
          setResultStatus(other.getResultStatus());
        }
        if (other.getPacketId() != 0) {
          setPacketId(other.getPacketId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PacketDataProto.PacketData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PacketDataProto.PacketData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ ;
      /**
       * <code>int32 cmd = 1;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>int32 cmd = 1;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int resultStatus_ ;
      /**
       * <code>int32 resultStatus = 3;</code>
       */
      public int getResultStatus() {
        return resultStatus_;
      }
      /**
       * <code>int32 resultStatus = 3;</code>
       */
      public Builder setResultStatus(int value) {
        
        resultStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 resultStatus = 3;</code>
       */
      public Builder clearResultStatus() {
        
        resultStatus_ = 0;
        onChanged();
        return this;
      }

      private int packetId_ ;
      /**
       * <code>int32 packetId = 4;</code>
       */
      public int getPacketId() {
        return packetId_;
      }
      /**
       * <code>int32 packetId = 4;</code>
       */
      public Builder setPacketId(int value) {
        
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packetId = 4;</code>
       */
      public Builder clearPacketId() {
        
        packetId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PacketData)
    }

    // @@protoc_insertion_point(class_scope:PacketData)
    private static final PacketDataProto.PacketData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PacketDataProto.PacketData();
    }

    public static PacketDataProto.PacketData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PacketData>
        PARSER = new com.google.protobuf.AbstractParser<PacketData>() {
      public PacketData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PacketData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PacketData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PacketData> getParserForType() {
      return PARSER;
    }

    public PacketDataProto.PacketData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PacketData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PacketData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027protos/PacketData.proto\"N\n\nPacketData\022" +
      "\013\n\003cmd\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\024\n\014resultStatu" +
      "s\030\003 \001(\005\022\020\n\010packetId\030\004 \001(\005B\021B\017PacketDataP" +
      "rotob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PacketData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PacketData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PacketData_descriptor,
        new java.lang.String[] { "Cmd", "Msg", "ResultStatus", "PacketId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
